name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ master ]   # change if your default branch is different
  workflow_dispatch:      # allow manual runs

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}   # enables PR comments/preview envs
          action: "upload"

          # ---- Paths (adjust to your repo) ----
          app_location: "/"        # where index.html lives; e.g. "/site" if in /site
          api_location: ""         # only if you have an Azure Functions API
          output_location: ""      # set to your build output (e.g., "dist") if you build
